name: FigureEditor
version: 0.0.1
author: Viktor Dakalov <atlantidu@gmail.com>
description: Реализация простого редактора геометрических фигур на FrameUI
homepage: http://www.vihtor.ru
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  FrameUI:
    git:
      url: git@github.com:vdakalov/FrameUI.git
      ref: lib
  script_inliner: '>=1.0.0 <2.0.0'
transformers:
- script_inliner
