name: FigureEditor
version: 0.0.1
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  FrameUI:
    git: git@github.com:vdakalov/FrameUI.git
  script_inliner: ">=1.0.0 <2.0.0"
transformers:
  - script_inliner